[package]
name = "prolapse"
version = "0.1.0"
authors = ["Andrew Baxter <rhinocratic@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "^0.1.10"
google-drive3 = "^1.0.10"
chrono = "0.3"
